### PR TITLE
Lorem ipsum text substituted

### PR DESCRIPTION
**Pull request by mavhezha**

### CODE REVIEW

**Comment by malgamves** [comment]
Great work 👍 
Apologies for checking it late

**Comment by malgamves** [comment]
You missed the Lorem text [here](https://uniphyd.club/index.html) got it though.

**Comment by mavhezha** [comment]
oooooooh, i wanted you to check the changes which i have made first so that
i can proceed to the rest of the site

**Comment by malgamves** [comment]
Yeah I remembered you told me that in person. My bad.

**Pull request merged**
