### PR TITLE
Update

### PR DESCRIPTION
**Pull request by rishabh-327**
-Blurry BG removed.
-Follow column width adjusted to look better in mobile devices.
-Sections for Mendix session added.

### CODE REVIEW

**Comment by rishabh-327** [comment]
@malgamves check out this PR.

**Comment by rishabh-327** [comment]
Lorem ipsum in the Mendix section needs to be replaced. Add relevant content and uncomment the section. @mavhezha

**Comment by rishabh-327** [comment]
Also link the social handles on about us page team section.

**Comment by mavhezha** [comment]
noted bro, i will work on it this weekend. I am finishing my manuals and
assignments for the submissions

**Comment by rishabh-327** [comment]
Cool

**Pull request merged**
