### PR TITLE
Trasparent Image, CSS update.

### PR DESCRIPTION
**Pull request by rishabh-327**
About us page images now have transparent background.
CSS styles are now more organized and reusable.
Unnecessary classes have been removed.
Pages have been updated with the changed CSS.

### CODE REVIEW

**Comment by malgamves** [comment]
@rishabh-327 please drop a text when you open a pull request. Didn't see this. Checking it now

**Comment by malgamves** [comment]
Great work as usual @rishabh-327! 

image
The Uniphyd. text isný uniform, let's keep the same font as the text on the home page.
image
Also can we experiment with a white background maybe for the pages instead of the orange trIngular thing. It's a little blurry and doesnt look very sharp. Comment the images here and tag me so I can see how they look

**Comment by malgamves** [comment]
Was thinking of a simple white background. Let's see how that looks. Plain white

**Comment by rishabh-327** [comment]
What about these overlays, they work or need change? @malgamves 
ol
oll

**Comment by malgamves** [comment]
overlays are great!

**Comment by malgamves** [comment]
Lol, too much theory into what makes a great website. I'm lost

**Comment by rishabh-327** [comment]
Yeah, we really need(someone) to work on content !

**Comment by malgamves** [comment]
What content are you thinking of?

**Comment by rishabh-327** [comment]
About all the content on the site, from good summary on home page to a little detailed article about the meetup like what is was, how it went etc on other page. About us page also looks incomplete, no mention of how uniphyd established motive behind it. Bio of u guys. We do not even update the "upcoming" section prior to meetup(like today).

**Comment by malgamves** [comment]
I think you understand better why we need a content writer. We're working
on it. Try to look for one.
I'm doing the same. Did you make those changes?

*Daniel M. Phiri*
Twitter <https://twitter.com/malgamves>
LinkedIn <https://www.linkedin.com/in/daniel-phiri-92a044148/>
+91 7227840122

**Comment by rishabh-327** [comment]
Done with changes, opening PR soon.

**Pull request closed without merging**
